<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
	<UseWindowsForms>true</UseWindowsForms>
	  
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>

	<!-- Application -->
	<AssemblyName>RecipeItemCreator</AssemblyName>
	<Product>Recipe Item Creator</Product>
	<Version>1.0.0</Version>
	<AssemblyVersion>1.0.0.0</AssemblyVersion>
	<FileVersion>1.0.0.0</FileVersion>

	<!-- Single EXE -->
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<SelfContained>true</SelfContained>
	<PublishSingleFile>true</PublishSingleFile>

	<!-- Required for native libraries such as SkiaSharp -->
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

	<!-- Keep WinForms / SkiaSharp safe -->
	<PublishTrimmed>false</PublishTrimmed>

	<!-- Release output -->
	<DebugType>none</DebugType>
	<DebugSymbols>false</DebugSymbols>

	<!-- Smaller single-file executable -->
	<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
	<ApplicationIcon>Assets\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Build\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>